// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistemas_Distribuidos.Data;

#nullable disable

namespace Sistemas_Distribuidos.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20221207203139_AddDateTabHG1")]
    partial class AddDateTabHG1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sistemas_Distribuidos.Models.CorretoraModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float?>("buy")
                        .HasColumnType("real");

                    b.Property<string>("format_idioma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("format_moeda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("last")
                        .HasColumnType("real");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("sell")
                        .HasColumnType("real");

                    b.Property<DateTime>("updateAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("variation")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Corretoras");
                });

            modelBuilder.Entity("Sistemas_Distribuidos.Models.IndiceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("points")
                        .HasColumnType("real");

                    b.Property<DateTime>("updateAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("variation")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Indices");
                });

            modelBuilder.Entity("Sistemas_Distribuidos.Models.MoedaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("buy")
                        .HasColumnType("real");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("sell")
                        .HasColumnType("real");

                    b.Property<DateTime>("updateAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("variation")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Moedas");
                });

            modelBuilder.Entity("Sistemas_Distribuidos.Models.TaxaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("cdi")
                        .HasColumnType("real");

                    b.Property<float>("cdi_daily")
                        .HasColumnType("real");

                    b.Property<float>("daily_factor")
                        .HasColumnType("real");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<float>("selic")
                        .HasColumnType("real");

                    b.Property<float>("selic_daily")
                        .HasColumnType("real");

                    b.Property<DateTime>("updateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Taxas");
                });

            modelBuilder.Entity("Sistemas_Distribuidos.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExistingEmail")
                        .HasColumnType("bit");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
